[package]
name = "stack"
version = "0.0.1"
authors = ["aswna <aswna@server.fake>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
